# http://travis-ci.org/#!/jaraco/keyring

language: python

python:
  - 2.6
  - 2.7
  - 3.2

script:
  - if [[ $TRAVIS_PYTHON_VERSION == '3.2' ]]; then OPTS="build/lib"; fi
  - python setup.py ptr --addopts="-rs -v $OPTS"
